# Generated by Django 4.1.2 on 2023-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
